# Generated by Django 3.1.4 on 2021-04-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=45)),
                ('topic', models.CharField(max_length=100)),
                ('total_time', models.IntegerField()),
                ('teaching', models.IntegerField()),
                ('questioning', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'ordering': ('-created_at',),
            },
        ),
    ]
